In [1]:
from numpy import *
import numpy

#import SMLR
from SMLR import *

#import SVM from scikir-learn
import sklearn.svm

#prepare classifier objects
svm=sklearn.svm.LinearSVC(C=0.1)
smlr=SMLR(n_iter=100)

SMLR (sparse multinomial logistic regression)


In [2]:
smlr.get_params()
help(smlr.fit)

Help on method fit in module SMLR:

fit(self, feature, label) method of SMLR.SMLR instance
    fit(self, feature, label) method of SMLR instance
    Fit the model according to the given training data (in the same way as logistic.py in sklearn).
    
    Parameters
    ----------
    feature : array-like, shape = [n_samples, n_features]
            Training vector, where n_samples in the number of samples and
            n_features is the number of features.
    
    label : array-like, shape = [n_samples]
            Target vector for "feature"
    
    Returns
    -------
    self : object
    Returns self.



In [3]:
#sample data generation

# of samples
N=100

#label vector
label4training=numpy.vstack((numpy.zeros((N,1)),numpy.ones((N,1))))
label4test=numpy.vstack((numpy.zeros((N,1)),numpy.ones((N,1))))

#mean for each class
feature4class1=numpy.array([1,0,0,0,0,0,0,0,0,0])
feature4class2=numpy.array([-1,0,0,0,0,0,0,0,0,0])

feature4training=numpy.vstack(((numpy.dot(numpy.ones((N,1)),[feature4class1]),numpy.dot(numpy.ones((N,1)),[feature4class2]))))
feature4test=numpy.vstack(((numpy.dot(numpy.ones((N,1)),[feature4class1]),numpy.dot(numpy.ones((N,1)),[feature4class2]))))
import numpy.random
numpy.random.seed(seed=1)
feature4training=feature4training+0.5*numpy.random.randn(feature4training.shape[0],feature4training.shape[1])
feature4test=feature4test+0.5*numpy.random.randn(feature4test.shape[0],feature4test.shape[1])

In [4]:
#scatter plot in the feature space
import matplotlib.pyplot
for n in range(len(label4training)):
    if label4training[n]==0:
        matplotlib.pyplot.scatter(feature4training[n,0],feature4training[n,1],color='red')
    else:
        matplotlib.pyplot.scatter(feature4training[n,0],feature4training[n,1],color='blue')
matplotlib.pyplot.xlabel("Dimension 1")
matplotlib.pyplot.ylabel("Dimension 2")
import pylab
pylab.xlim(-3,3)
pylab.ylim(-3,3)
matplotlib.pyplot.show()

In [5]:
labels = label4training.ravel()
labels.shape



(200,)

In [6]:
#SMLR & SVM training
print "SMLR learning"
#smlr.fit(feature4training,label4training)
smlr.fit(feature4training,labels)
print "SVM learning"
#svm.fit(feature4training,label4training)
svm.fit(feature4training,labels)

SMLR learning
# of iterations: 1 ,  # of effective dimensions: 8
# of iterations: 20 ,  # of effective dimensions: 3
# of iterations: 40 ,  # of effective dimensions: 3
# of iterations: 60 ,  # of effective dimensions: 3
# of iterations: 80 ,  # of effective dimensions: 3
# of iterations: 100 ,  # of effective dimensions: 3
SVM learning


LinearSVC(C=0.1, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [7]:
print "The SLMR weights obtained"
print numpy.transpose(smlr.coef_)


The SLMR weights obtained
[[ 8.82755976 -8.82755976]
 [ 1.51092945 -1.51092557]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [-1.1942523   1.19425219]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]]


In [8]:
#linear boundary in the feature space
import matplotlib.pyplot
for n in range(len(label4training)):
    if label4training[n]==0:
        matplotlib.pyplot.scatter(feature4training[n,0],feature4training[n,1],color='red')
    else:
        matplotlib.pyplot.scatter(feature4training[n,0],feature4training[n,1],color='blue')
matplotlib.pyplot.xlabel("Dimension 1")
matplotlib.pyplot.ylabel("Dimension 2")
w=smlr.coef_[0,:]
x = numpy.arange(-5, 5, 0.001)
y = (-w[-1]-x*w[0])/w[1]
matplotlib.pyplot.plot(x,y,color='black')
import pylab
pylab.xlim(-3,3)
pylab.ylim(-3,3)
matplotlib.pyplot.show()

In [9]:
#generalization test
predictedLabelBySVM=svm.predict(feature4test)
predictedLabelBySMLR=smlr.predict(feature4test)

num_correct=0
for n in range(len(label4test)):
    if label4test[n]==predictedLabelBySVM[n]:
        num_correct=num_correct+1
SVMaccuracy=numpy.double(num_correct)/len(label4test)*100

num_correct=0
for n in range(len(label4test)):
    if label4test[n]==predictedLabelBySMLR[n]:
        num_correct=num_correct+1
SMLRaccuracy=numpy.double(num_correct)/len(label4test)*100

print "SVM accuracy: %s"%(SVMaccuracy)
print "SMLR accuracy: %s"%(SMLRaccuracy)

SVM accuracy: 98.0
SMLR accuracy: 98.0


In [10]:
help(smlr.score)

Help on method score in module sklearn.base:

score(self, X, y, sample_weight=None) method of SMLR.SMLR instance
    Returns the mean accuracy on the given test data and labels.
    
    In multi-label classification, this is the subset accuracy
    which is a harsh metric since you require for each sample that
    each label set be correctly predicted.
    
    Parameters
    ----------
    X : array-like, shape = (n_samples, n_features)
        Test samples.
    
    y : array-like, shape = (n_samples) or (n_samples, n_outputs)
        True labels for X.
    
    sample_weight : array-like, shape = [n_samples], optional
        Sample weights.
    
    Returns
    -------
    score : float
        Mean accuracy of self.predict(X) wrt. y.



In [11]:
smlr.score(feature4test,label4test)

0.97999999999999998

In [12]:
round(0.4)

0.0

In [13]:
log(2.055158e-15)

-33.818423664273269

In [14]:
smlr.predict_proba(feature4training)

array([[  1.00000000e+00,   2.05515847e-15],
       [  1.00000000e+00,   3.22462661e-13],
       [  9.99972061e-01,   2.79385258e-05],
       [  9.99982705e-01,   1.72945506e-05],
       [  9.99999791e-01,   2.08929203e-07],
       [  9.99999995e-01,   5.21310124e-09],
       [  9.99997691e-01,   2.30859011e-06],
       [  9.98586011e-01,   1.41398887e-03],
       [  9.99999761e-01,   2.38941387e-07],
       [  1.00000000e+00,   4.51575816e-13],
       [  9.99999786e-01,   2.14292780e-07],
       [  9.99488282e-01,   5.11718153e-04],
       [  9.99999623e-01,   3.77268930e-07],
       [  9.99999874e-01,   1.25594478e-07],
       [  9.99999847e-01,   1.53435855e-07],
       [  9.99988328e-01,   1.16721594e-05],
       [  9.99992440e-01,   7.55992546e-06],
       [  9.99998730e-01,   1.26963298e-06],
       [  9.99515818e-01,   4.84182207e-04],
       [  1.00000000e+00,   6.27306534e-14],
       [  9.99999974e-01,   2.60287962e-08],
       [  9.99991692e-01,   8.30813333e-06],
       [  

In [15]:
smlr.predict_log_proba(feature4training)

array([[ -1.99840144e-15,  -3.38184234e+01],
       [ -3.22519789e-13,  -2.87627890e+01],
       [ -2.79389161e-05,  -1.04855040e+01],
       [ -1.72947002e-05,  -1.09651191e+01],
       [ -2.08929225e-07,  -1.53812704e+01],
       [ -5.21310119e-09,  -1.90720909e+01],
       [ -2.30859277e-06,  -1.29788736e+01],
       [ -1.41498950e-03,  -6.56134058e+00],
       [ -2.38941416e-07,  -1.52470476e+01],
       [ -4.51527704e-13,  -2.84260331e+01],
       [ -2.14292803e-07,  -1.53559226e+01],
       [ -5.11849125e-04,  -7.57773657e+00],
       [ -3.77269001e-07,  -1.47903076e+01],
       [ -1.25594486e-07,  -1.58902075e+01],
       [ -1.53435867e-07,  -1.56899832e+01],
       [ -1.16722275e-05,  -1.13583041e+01],
       [ -7.55995404e-06,  -1.17926492e+01],
       [ -1.26963378e-06,  -1.35767827e+01],
       [ -4.84299461e-04,  -7.63304926e+00],
       [ -6.27276009e-14,  -3.03999262e+01],
       [ -2.60287966e-08,  -1.74640624e+01],
       [ -8.30816784e-06,  -1.16982756e+01],
       [ -

In [16]:
smlr.get_params()


{'n_iter': 100, 'verbose': 1}

In [17]:
smlr

SMLR(n_iter=100, verbose=1)